### PR TITLE
add google geocode autocomplete

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
Screenshot 2023-12-17 at 7 41 24 PM

**Comment by dgershman** [comment]
What is the impact on the Google api key?

**Comment by pjaudiomv** [comment]
> What is the impact on the Google api key?

ah yes I think may need to enable Places API. looks like you get 500,000 api calls for free a month

**Comment by dgershman** [comment]
Ok I’m using my api key; I’m concerned with the potential impact on a feature that provides little or no value.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgershman** [comment]
I think it’s mine, not actually sure.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pjaudiomv** [comment]
It's fine I'll swap it out for a new key from my account to alleviate that concern . the value is in the autocomplete, I use sdle a lot and I've often wished it had autocomplete when typing locations

**Review by dgershman — APPROVED** [review]

**Pull request merged**
